apiVersion: apps/v1
kind: Deployment
metadata:
  name: yafig-user-python
  labels:
    app: yafig-user-python
spec:
  selector:
    matchLabels:
      app: yafig-user-python
      tier: api-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: yafig-user-python
        tier: api-server
    spec:
      containers:
      - image: yafig-user-python
        name: yafig-user-python
---
apiVersion: v1
kind: Service
metadata:
  name: yafig-user-service
  labels:
    app: yafig-user-python
spec:
  ports:
    - port: 5000
  selector:
    app: yafig-user-python
    tier: api-server
  type: ClusterIP